### ISSUE TITLE
Aftman error: Tried to run an Aftman-managed version

### ISSUE THREAD

**Issue by kedoska** [Roblox-Journey/project-boilerplate#1]
Hi there,

Thanks you for your work here.

After following the readme and installing dependencies, specifically

```bash
foreman install
```

I was receiving the following error:

```error
rojo build -o "project-boilerplate.rbxlx"
Aftman error: Tried to run an Aftman-managed version of rojo, but no aftman.toml files list this tool.
To run rojo from this directory, add it to one of these files:
```

So I installed rojo globally with `aftman add --global rojo-rbx/rojo`

My suggestion is to show which dependencies are installed by `foreman` and which must be installed on the dev machine.

Thanks again...

**Comment by dev-jhon-yo** [comment]
Thanks for raising this issue @kedoska! Your feedback is super important as we always seek to improve our project. I'm currently out of time, but I intend to update this project soon and make it more complete and functional. 🚀 ✨
